[package]
name = "postana"
version = "0.1.0"
edition = "2021"

[dependencies]
detector = { path = "../detector" }
clap = { version = "3", features = ["derive"] }
glob = "0.3"
memmap2 = "0.5"
cursive = "0.18"
opener = "0.5"
tempfile = "3"
midasio = "0.4"
pgfplots = "0.4"
