[package]
name = "alpha-g-analysis"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Executables that perform common post-processing/offline analysis on the data of the ALPHA-g experiment"
readme = "README.md"
repository = "https://github.com/DJDuque/alpha-g"
keywords = ["alpha", "alpha-g", "cern", "physics", "antimatter"]
categories = ["science", "command-line-utilities"]

[dependencies]
alpha_g_detector = { version = "0.2",  path = "../detector" }
anyhow = "1"
clap = { version = "4", features = ["derive"] }
cursive = "0.20"
glob = "0.3"
indicatif = "0.17"
lz4 = "1"
memmap2 = "0.5"
midasio = "0.4"
opener = "0.5"
pgfplots = "0.5"
serde_json = "1"
tempfile = "3"
